version: "3.1"

services:
  mycontainer:
    # image: eza-linux-build
    build: .
    volumes:
    - type: bind
      target: /usr/src/eza/release
      source: ${PWD}/release
      bind:
        create_host_path: true
    #       context: ../.
    #       dockerfile: ./Dockerfile
