# SPDX-FileCopyrightText: 2024 Christina Sørensen
# SPDX-License-Identifier: EUPL-1.2
#
# SPDX-FileCopyrightText: 2023-2024 Christina Sørensen, eza contributors
# SPDX-FileCopyrightText: 2014 Benjamin Sago
# SPDX-License-Identifier: MIT
blank_issues_enabled: true
