# SPDX-FileCopyrightText: 2024 Christina Sørensen
# SPDX-License-Identifier: EUPL-1.2
#
# SPDX-FileCopyrightText: 2023-2024 Christina Sørensen, eza contributors
# SPDX-FileCopyrightText: 2014 Benjamin Sago
# SPDX-License-Identifier: MIT
name: Publish to Winget
on:
  release:
    types: [released]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: eza-community.eza
          installers-regex: '-pc-windows-gnu\.zip$'
          token: ${{ secrets.WINGET_TOKEN }}
